set -g default-terminal "tmux-256color"
set-window-option -g mode-keys vi
set -g status-position top
set -g base-index 1
set -g pane-base-index 1
set -g mouse on
set -s set-clipboard on
set -gq allow-passthrough on
set -g visual-activity off
set-option -g focus-events on
set -g renumber-windows on
set -g history-limit 50000

bind-key r source-file ~/.tmux.conf

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi Escape send -X cancel

separator_right=""
set -g window-status-style "fg=#3a7292"
set -g window-status-current-style "fg=#f9f7f6 ,bold , bg=#3a7292"
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "

set -g display-panes-colour "#3a7292"
set -g display-panes-active-colour "#c36022"

set -g status-style "fg=#4d4851, bg=#f9f7f6"
set -g status-left-length 60
set -g status-right-length 60
set -g status-left  "#[fg=#3a7292,bold] #S #[default] "
set -g status-right "#[fg=#4d4851] %H:%M #[fg=#3a7292,bold] #H "

set -g message-style "fg=#614096"
set -g mode-style "fg=#4d4851, bg=#a4c7db"

set -g @vim_navigator_mapping_left "C-Left C-h"
set -g @vim_navigator_mapping_right "C-Right C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"

set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "christoomey/vim-tmux-navigator"
set -g @plugin "tmux-plugins/tmux-yank"

if-shell 'test -n "$SSH_CLIENT"' \
    'source-file ~/.tmux.remote.conf'

bind -T root F12 \
    set prefix None \;\
    set key-table off \;\
    set status-style "fg=#f9f7f6,bg=#97909D" \;\
    set window-status-current-format " #I:#W " \;\
    set window-status-current-style "fg=#f9f7f6,bold,bg=#97909D" \;\
    if -F '#{pane_in_mode}' 'send-keys -X cancel' \;\
    refresh-client -S

bind -T off F12 \
    set -u prefix \;\
    set -u key-table \;\
    set -u status-style \;\
    set -u window-status-current-style \;\
    set -u window-status-current-format \;\
    refresh-client -S

run "~/.tmux/plugins/tpm/tpm"
