# Wayland, Decoding
gpu-context=wayland
vo=gpu-next
fullscreen=no
hwdec=auto

# Bild
scale=ewa_lanczos
dscale=mitchell
correct-downscaling=yes
sigmoid-upscaling=yes

# HDR / Tonemapping
hdr-compute-peak=yes
tone-mapping=bt.2446a

# Verhalten
save-position-on-quit=no
keep-open=yes
screenshot-directory=~/Bilder/Screenshots/
geometry=70%x70%

# Cache
cache=yes
demuxer-max-bytes=150MiB
