term=xterm-256color

font=Maple Mono NF:size=13
# line-height=<font metrics>
# letter-spacing=0
# horizontal-letter-offset=0
# vertical-letter-offset=0
# underline-offset=<font metrics>
# underline-thickness=<font underline thickness>
# strikeout-thickness=<font strikeout thickness>
# box-drawings-uses-font-glyphs=no
dpi-aware=no
# gamma-correct-blending=no

initial-color-theme=light
pad=3x0
# bold-text-in-bright=no

[security]
osc52=enabled  # disabled|copy-enabled|paste-enabled|enabled
[cursor]
style=block
blink=no

[mouse]
hide-when-typing=yes

[colors-light]
background=f9f7f6
foreground=4d4851

regular0=4d4851
regular1=a63f3f
regular2=3a784c
regular3=c36022
regular4=3a7292
regular5=614096
regular6=4c5aa9
regular7=e4ded7

bright0=817887
bright1=d6a9a9
bright2=a9d6b6
bright3=edbb9b
bright4=a4c7db
bright5=c7b7e1
bright6=aeb4da
bright7=e4ded7

selection-foreground=4d4851
selection-background=e4ded7

[colors-dark]
background=100e11
foreground=e9e6e2

regular0=100e11
regular1=d36969
regular2=59c076
regular3=e08852
regular4=69acd3
regular5=a381da
regular6=eabf3e
regular7=d4cfd6

bright0=8d8593
bright1=d36969
bright2=59c076
bright3=e08852
bright4=69acd3
bright5=a381da
bright6=eabf3e
bright7=d4cfd6

selection-background=29252d
selection-foreground=e9e6e2
