term=xterm-256color

font=Maple Mono NF:size=13
# line-height=<font metrics>
# letter-spacing=0
# horizontal-letter-offset=0
# vertical-letter-offset=0
# underline-offset=<font metrics>
# underline-thickness=<font underline thickness>
# strikeout-thickness=<font strikeout thickness>
# box-drawings-uses-font-glyphs=no
dpi-aware=no
# gamma-correct-blending=no

include=~/.local/state/theme/foot-colors.ini
pad=3x0
# bold-text-in-bright=no

[security]
osc52=enabled  # disabled|copy-enabled|paste-enabled|enabled
[cursor]
style=block
blink=no

[mouse]
hide-when-typing=yes
