#!/usr/bin/env bash
set -euo pipefail

if pidof systemd-inhibit >/dev/null; then
    killall systemd-inhibit
else
    systemd-inhibit --what=idle --why="Caffeine Modus" --who="User" sleep infinity &
fi
