#!/usr/bin/env bash
set -e

FONT_BASE_DIR="${HOME}/.local/share/fonts"

log() {
    local level="$1"
    shift
    echo -e "[$(date '+%H:%M:%S')] [${level}] $*"
}

if ! command -v unzip >/dev/null 2>&1; then
    log "ERROR" "Unzip not installed. Aborting..."
    exit 1
fi

install_font() {
    local font_name="$1"
    local font_url="$2"

    local target_dir="${FONT_BASE_DIR}/${font_name}"
    local temp_zip="/tmp/${font_name}.zip"
    local temp_extract="/tmp/${font_name}_extract"

    mkdir -p "${target_dir}"
    mkdir -p "${temp_extract}"

    log "INFO" "Downloading ${font_name}..."
    curl -L "${font_url}" -o "${temp_zip}"

    log "INFO" "Extracting and filtering .ttf files..."
    unzip -oq "${temp_zip}" -d "${temp_extract}"
    find "${temp_extract}" -type f \( -name "*.[ot][tf][cc]" -o -name "*.[ot]tf" \) -exec mv {} "${target_dir}/" \;

    log "INFO" "Cleaning up..."
    rm "${temp_zip}"
    rm -rf "${temp_extract}"

    log "INFO" "${font_name} is located in ${target_dir}"

}

install_font "Maple_Mono_NF" "https://github.com/subframe7536/maple-font/releases/download/v7.9/MapleMono-NF-unhinted.zip"
install_font "Geist" "https://github.com/vercel/geist-font/releases/download/1.8.0/geist-font-1.8.0.zip"
install_font "Noto_CJK_Serif" "https://github.com/googlefonts/noto-cjk/releases/download/Serif2.003/01_NotoSerifCJK.ttc.zip"
install_font "Noto_CJK_Sans" "https://github.com/googlefonts/noto-cjk/raw/main/Sans/SuperOTC/NotoSansCJK.ttc.zip"
install_font "Libertinus" "https://github.com/alerque/libertinus/releases/download/v7.051/Libertinus-7.051.zip"

log "INFO" "Updating font cache..."
fc-cache -f

log "INFO" "Installation complete! Fonts located in ${FONT_BASE_DIR}"
