#!/usr/bin/env bash
set -euo pipefail

if ! git stash; then
    echo "Failed to stash changes." >&2
    exit 1
fi

if ! git pull; then
    echo "Failed to pull updates." >&2
    exit 1
fi

if ! git stash pop; then
    echo "Conflict during stash pop. Resolve it manually." >&2
    exit 1
fi

message=""

if [[ $# -eq 1 ]]; then
    message="$1"
else
    message="Update $(date +%Y-%m-%d_%H-%M)"
fi

git add --all
git commit -m "${message}"
git push
