#!/usr/bin/env bash

fixed_paths=(
	~/
	~/projects
	~/bookmarks
	~/repos
)

search_paths=(
	~/projects
	~/bookmarks
	~/repos
)

if [[ $# -eq 1 ]]; then
	selected=$1
else
	options=("${fixed_paths[@]}")

	while IFS= read -r line; do
		options+=("$line")
	done < <(find "${search_paths[@]}" -mindepth 1 -maxdepth 1 \( -type d -o -xtype d \) 2>/dev/null)

	selected=$(printf "%s\n" "${options[@]}" | fzf --bind "esc:abort")
fi

if [[ -z $selected ]]; then
	exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
	tmux new-session -s "${selected_name}" -c "${selected}"
	exit 0
fi

if ! tmux has-session -t="${selected_name}" 2>/dev/null; then
	tmux new-session -ds "${selected_name}" -c "${selected}"
fi

if [[ -z $TMUX ]]; then
	tmux attach-session -t "${selected_name}"
else
	tmux switch-client -t "${selected_name}"
fi
