local lush = require("lush")
local hsl = lush.hsl

---@diagnostic disable: undefined-global
local theme = lush(function(injected_functions)
    local sym = injected_functions.sym
    local p = {
        -- Dark theme palette
        -- Background colors (inverted light/dark)
        black_0 = hsl(30, 20, 10), -- Darkest background
        black_1 = hsl(30, 20, 20),
        black_2 = hsl(30, 20, 30), -- Derived from black_1
        gray_0 = hsl(275, 6, 50),
        gray_1 = hsl(275, 6, 60),
        white_0 = hsl(30, 20, 80), -- Lightest background
        white_1 = hsl(30, 20, 90), -- Lighter background
        white_2 = hsl(30, 20, 95), -- Derived from white_1

        -- Foreground colors (inverted from original bg colors)
        red_0 = hsl(0, 45, 65),
        red_1 = hsl(0, 45, 75),
        red_bg_0 = hsl(0, 35, 25),
        red_bg_1 = hsl(0, 35, 35),

        orange_0 = hsl(23, 70, 65),
        orange_1 = hsl(23, 70, 75),
        orange_bg_0 = hsl(23, 70, 25),
        orange_bg_1 = hsl(23, 70, 35),

        yellow_0 = hsl(45, 80, 65),
        yellow_1 = hsl(45, 80, 75),
        yellow_bg_0 = hsl(45, 80, 25),
        yellow_bg_1 = hsl(45, 80, 35),

        green_0 = hsl(137, 35, 65),
        green_1 = hsl(137, 35, 75),
        green_bg_0 = hsl(137, 35, 25),
        green_bg_1 = hsl(137, 35, 35),

        cyan_0 = hsl(202, 43, 65),
        cyan_1 = hsl(202, 43, 75),
        cyan_bg_0 = hsl(202, 43, 25),
        cyan_bg_1 = hsl(202, 43, 35),

        blue_0 = hsl(231, 38, 65),
        blue_1 = hsl(231, 38, 75),
        blue_bg_0 = hsl(231, 38, 25),
        blue_bg_1 = hsl(231, 38, 35),

        violet_0 = hsl(263, 40, 65),
        violet_1 = hsl(263, 40, 75),
        violet_bg_0 = hsl(263, 40, 25),
        violet_bg_1 = hsl(263, 40, 35),

        magenta_0 = hsl(354, 50, 65),
        magenta_1 = hsl(340, 50, 75),
        magenta_bg_0 = hsl(340, 50, 25),
        magenta_bg_1 = hsl(340, 50, 35),

        -- Pure accent colors
        red = hsl(0, 100, 60),
        yellow = hsl(50, 100, 60),
        green = hsl(100, 100, 50),
        blue = hsl(210, 100, 60),
        violet = hsl(290, 100, 60),
        gray = hsl(0, 0, 60),
    }
    return {
        ColorColumn({ fg = p.gray_1, bg = nil }),
        Conceal({ fg = p.gray_0, bg = nil }),
        Cursor({}),
        CurSearch({ fg = Normal.fg, bg = p.green_bg_0 }),
        lCursor({ Cursor }),
        CursorIM({ Cursor }),
        CursorColumn({ fg = p.gray_1, bg = nil }),
        CursorLine({ fg = nil, bg = p.black_1 }),
        Directory({ fg = p.cyan_1, bg = nil }),
        Removed({ fg = nil, bg = p.red_bg_0 }),
        Added({ fg = nil, bg = p.green_bg_0 }),
        Changed({ fg = nil, bg = p.yellow_bg_0 }),
        DiffAdd({ Added }),
        DiffDelete({ Removed }),
        DiffChange({ Changed }),
        DiffText({ fg = nil, bg = p.blue_bg_0, gui = "italic" }),
        TermCursor({ Cursor }),
        TermCursorNC({ fg = nil, bg = p.black_2 }),
        ErrorMsg({ fg = p.red_0, gui = "italic" }),

        IncSearch({ fg = Normal.fg, bg = p.green_bg_0 }),
        Substitute({ fg = Normal.fg, bg = p.yellow_bg_0 }),
        LineNr({ fg = p.gray_0, bg = nil }),
        LineNrAbove({ LineNr }),
        LineNrBelow({ LineNr }),
        CursorLineNr({ fg = p.white_0, bg = CursorLine.bg, gui = "bold" }),

        MatchParen({ fg = p.cyan_1, bg = p.cyan_bg_1 }),
        ModeMsg({ fg = p.green_0, bg = nil }),
        MsgArea({ fg = p.gray_1, bg = nil }),
        MsgSeparator({ MsgArea }),
        MoreMsg({ fg = p.cyan_1, bg = nil }),
        NonText({ fg = p.gray_0, bg = nil }),
        Normal({ fg = p.white_0, bg = p.black_0 }),
        NormalFloat({ fg = nil, bg = p.black_0 }),
        FloatBorder({ fg = p.cyan_1, bg = p.black_0 }),
        FloatTitle({ fg = p.cyan_1, bg = p.black_0 }),
        NormalNC({ Normal }),
        Pmenu({ fg = Normal.fg, bg = p.black_0 }),
        PmenuSel({ fg = Pmenu.fg, bg = p.black_1, gui = "bold" }),
        PmenuKind({ fg = p.cyan_0, bg = Pmenu.bg }),
        PmenuKindSel({ fg = PmenuKind.fg, bg = PmenuSel.bg }),
        PmenuExtra({ Pmenu, gui = "italic" }),
        PmenuExtraSel({ PmenuSel, gui = "italic,bold" }),

        Question({ fg = p.cyan_0, bg = nil }),
        QuickFixLine({ fg = p.cyan_0, bg = nil }),
        Search({ fg = Normal.fg, bg = p.yellow_bg_0 }),
        SpecialKey({ fg = p.gray_0, bg = nil }),
        SpellBad({ fg = nil, bg = nil, sp = p.red, gui = "underline" }),
        SpellCap({ fg = nil, bg = nil, sp = p.gray, gui = "underline" }),
        SpellLocal({ fg = nil, bg = nil, sp = p.blue, gui = "underline" }),
        SpellRare({ fg = nil, bg = nil, sp = p.violet, gui = "underline" }),
        StatusLine({ fg = nil, bg = p.black_1 }),
        StatusLineNC({ StatusLine }),
        Title({ fg = p.cyan_1, bg = nil, gui = "bold" }),
        Visual({ fg = nil, bg = p.cyan_bg_0 }),

        WarningMsg({ fg = p.yellow_0, bg = nil }),
        Whitespace({ fg = p.gray_0, bg = nil }),
        Winseparator({ fg = p.black_0, bg = nil }),
        WildMenu({ PmenuSel }),

        Comment({ fg = p.gray_0, bg = nil, gui = "italic" }),

        Constant({ fg = p.yellow_0, bg = nil }),
        String({ fg = p.green_0, bg = nil, gui = "italic" }),
        Character({ fg = p.violet_0, bg = nil }),
        Number({ fg = p.orange_0, bg = nil }),
        Boolean({ fg = p.orange_0, bg = nil }),
        Float({ fg = p.orange_0, bg = nil }),

        Identifier({ fg = p.blue_1, bg = nil }),
        Function({ fg = p.cyan_0, bg = nil }),

        Statement({ fg = p.white_0, bg = nil, gui = "bold" }),
        Conditional({ fg = p.magenta_0, bg = nil, gui = "italic" }),
        Repeat({ Conditional }),
        Label({ Conditional }),
        Operator({ fg = p.blue_0, bg = nil }),
        Keyword({ fg = p.magenta_0, bg = nil }),
        Exception({ fg = p.violet_0, bg = nil, gui = "italic" }),

        PreProc({ fg = p.red_0, bg = nil }),
        Include({ PreProc }),
        Define({ PreProc }),
        Macro({ PreProc }),
        PreCondit({ PreProc }),

        Type({ fg = p.magenta_1, bg = nil }),
        StorageClass({ Type }),
        Structure({ Type }),
        Typedef({ Type }),

        Special({ fg = p.cyan_0, bg = nil }),
        SpecialChar({ Special }),
        Tag({ Special }),
        Delimiter({ fg = p.violet_0, bg = nil }),
        SpecialComment({ Special }),
        Debug({ fg = p.blue_0, bg = nil, gui = "italic" }),

        Underlined({ fg = nil, bg = nil, gui = "underline" }),
        Ignore({ fg = nil, bg = nil }),
        Error({ fg = p.white_0, bg = p.red_bg_0, gui = "bold" }),
        Todo({ fg = p.white_0, bg = p.yellow_bg_0, gui = "bold" }),

        LspReferenceText({
            fg = p.white_0,
            bg = p.blue_bg_0,
            gui = "underline",
        }),
        LspReferenceRead({ LspReferenceText, fg = p.blue_1 }),
        LspReferenceWrite({ LspReferenceText, fg = p.green_1 }),
        LspCodeLens({ fg = p.gray_1, bg = nil, gui = "italic" }),
        LspCodeLensSeparator({ LspCodeLens }),
        LspSignatureActiveParameter({ fg = p.white_0, bg = p.cyan_bg_0 }),

        DiagnosticError({ fg = p.red_0, bg = nil }),
        DiagnosticWarn({ fg = p.yellow_0, bg = nil }),
        DiagnosticInfo({ fg = p.gray_1, bg = nil }),
        DiagnosticHint({ fg = p.cyan_0, bg = nil }),
        DiagnosticOk({ fg = p.green_0, bg = nil }),
        DiagnosticVirtualTextError({ DiagnosticError }),
        DiagnosticVirtualTextWarn({ DiagnosticWarn }),
        DiagnosticVirtualTextInfo({ DiagnosticInfo }),
        DiagnosticVirtualTextHint({ DiagnosticHint }),
        DiagnosticVirtualTextOk({ DiagnosticOk }),
        DiagnosticUnderlineError({ gui = "underline", sp = DiagnosticError.fg }),
        DiagnosticUnderlineWarn({ gui = "underline", sp = DiagnosticWarn.fg }),
        DiagnosticUnderlineInfo({ gui = "underline", sp = DiagnosticInfo.fg }),
        DiagnosticUnderlineHint({ gui = "underline", sp = DiagnosticHint.fg }),
        DiagnosticUnderlineOk({ gui = "underline", sp = DiagnosticOk.fg }),
        DiagnosticFloatingError({ DiagnosticError }),
        DiagnosticFloatingWarn({ DiagnosticWarn }),
        DiagnosticFloatingInfo({ DiagnosticInfo }),
        DiagnosticFloatingHint({ DiagnosticHint }),
        DiagnosticFloatingOk({ DiagnosticOk }),
        DiagnosticSignError({ DiagnosticError }),
        DiagnosticSignWarn({ DiagnosticWarn }),
        DiagnosticSignInfo({ DiagnosticInfo }),
        DiagnosticSignHint({ DiagnosticHint }),
        DiagnosticSignOk({ DiagnosticOk }),

        sym("@text.literal")({ Comment }),
        sym("@text.reference")({ Identifier }),
        sym("@text.title")({ Title }),
        sym("@text.uri")({ Underlined }),
        sym("@text.underline")({ Underlined }),
        sym("@text.todo")({ Todo }),
        sym("@comment")({ Comment }),
        sym("@punctuation")({ Special }),
        sym("@constant")({ Constant }),
        sym("@constant.builtin")({ Special }),
        sym("@constant.macro")({ Define }),
        sym("@define")({ Define }),
        sym("@macro")({ Macro }),
        sym("@string")({ String }),
        sym("@string.escape")({ SpecialChar }),
        sym("@string.special")({ SpecialChar }),
        sym("@character")({ Character }),
        sym("@character.special")({ SpecialChar }),
        sym("@number")({ Number }),
        sym("@boolean")({ Boolean }),
        sym("@float")({ Float }),
        sym("@function")({ Function }),
        sym("@function.builtin")({ Function }),
        sym("@function.macro")({ Function }),
        sym("@parameter")({ Identifier }),
        sym("@method")({ Function }),
        sym("@field")({ Identifier }),
        sym("@property")({ Identifier }),
        sym("@constructor")({ Special }),
        sym("@conditional")({ Conditional }),
        sym("@repeat")({ Repeat }),
        sym("@label")({ Label }),
        sym("@operator")({ Operator }),
        sym("@keyword")({ Keyword }),
        sym("@exception")({ Exception }),
        sym("@variable")({ Identifier }),
        sym("@type")({ Type }),
        sym("@type.definition")({ Typedef }),
        sym("@storageclass")({ StorageClass }),
        sym("@structure")({ Structure }),
        sym("@namespace")({ Identifier }),
        sym("@include")({ Include }),
        sym("@preproc")({ PreProc }),
        sym("@debug")({ Debug }),
        sym("@tag")({ Tag }),
        sym("@markup.link")({ Underlined, fg = p.blue_0 }),
        sym("@markup.italic")({ fg = p.green_0, bg = nil, gui = "italic" }),
        sym("@markup.strong")({ fg = p.magenta_0, bg = nil, gui = "bold" }),
        sym("@diff.minus")({ DiffDelete }),
        sym("@diff.plus")({ DiffAdd }),
        sym("@diff.delta")({ DiffChange }),

        GitSignsAdd({ fg = p.green, bg = nil }),
        GitSignsAddLn({ GitSignsAdd }),
        GitSignsAddInline({ GitSignsAdd }),
        GitSignsChange({ fg = p.yellow, bg = nil }),
        GitSignsChangeLn(GitSignsChange),
        GitSignsChangeInline(GitSignsChange),
        GitSignsDelete({ fg = p.red, bg = nil }),
        GitSignsDeleteLn({ GitSignsDelete }),
        GitSignsDeleteInline({ GitSignsDelete }),
        GitSignsUntracked({ fg = p.blue, bg = nil }),
        GitSignsUntrackedLn({ GitSignsUntracked }),
        GitSignsUntrackedInline({ GitSignsUntracked }),

        NotifyDEBUGBorder({ fg = p.cyan_0, bg = nil }),
        NotifyDEBUGIcon({ NotifyDEBUGBorder }),
        NotifyDEBUGTitle({ NotifyDEBUGBorder }),
        NotifyERRORBorder({ fg = p.red_0, bg = nil }),
        NotifyERRORIcon({ NotifyERRORBorder }),
        NotifyERRORTitle({ NotifyERRORBorder }),
        NotifyINFOBorder({ fg = p.blue_0, bg = nil }),
        NotifyINFOIcon({ NotifyINFOBorder }),
        NotifyINFOTitle({ NotifyINFOBorder }),
        NotifyTRACEBorder({ fg = p.green_0, bg = nil }),
        NotifyTRACEIcon({ NotifyTRACEBorder }),
        NotifyTRACETitle({ NotifyTRACEBorder }),
        NotifyWARNBorder({ fg = p.yellow_0, bg = nil }),
        NotifyWARNIcon({ NotifyWARNBorder }),
        NotifyWARNTitle({ NotifyWARNBorder }),

        BlinkCmpKind({ fg = p.cyan_0 }),

        MiniStatuslineDevinfo({ fg = p.cyan_0, bg = p.black_1 }),
        MiniStatuslineFileinfo({ MiniStatuslineDevinfo }),
        MiniStatuslineFilename({ fg = p.white_0, bg = p.black_0 }),
        MiniStatuslineInactive({ StatusLineNC }),
        MiniStatuslineModeCommand({
            fg = p.black_0,
            bg = p.blue_0,
            gui = "bold",
        }),
        MiniStatuslineModeInsert({
            fg = p.black_0,
            bg = p.green_0,
            gui = "bold",
        }),
        MiniStatuslineModeNormal({
            fg = p.black_0,
            bg = p.cyan_0,
            gui = "bold",
        }),
        MiniStatuslineModeVisual({
            fg = p.black_0,
            bg = p.magenta_0,
            gui = "bold",
        }),
        MiniStatuslineModeOther({
            fg = p.black_0,
            bg = p.white_0,
            gui = "bold",
        }),
        MiniStatuslineModeReplace({
            fg = p.black_0,
            bg = p.violet_0,
            gui = "bold",
        }),

        RenderMarkdownBullet({ fg = p.cyan_0, bg = nil }),
        RenderMarkdownChecked({ DiagnosticOk }),
        RenderMarkdownUnchecked({ DiagnosticWarn }),
        RenderMarkdownCode({ fg = nil, bg = p.violet_bg_0 }),
        RenderMarkdownCodeInline({ fg = p.violet_0, bg = p.violet_bg_0 }),
        RenderMarkdownDash({ RenderMarkdownBullet }),
        RenderMarkdownDash({ RenderMarkdownBullet }),
        RenderMarkdownH1({ fg = p.red_0, bg = nil }),
        RenderMarkdownH1Bg({ fg = p.white_0, bg = p.red_bg_0, gui = "bold" }),
        RenderMarkdownH2({ fg = p.yellow_0, bg = nil }),
        RenderMarkdownH2Bg({ fg = p.white_0, bg = p.yellow_bg_0, gui = "bold" }),
        RenderMarkdownH3({ fg = p.cyan_0, bg = nil }),
        RenderMarkdownH3Bg({ fg = p.white_0, bg = p.cyan_bg_0, gui = "bold" }),
        RenderMarkdownH4({ fg = p.orange_0, bg = nil }),
        RenderMarkdownH4Bg({ fg = p.white_0, bg = p.orange_bg_0, gui = "bold" }),
        RenderMarkdownH5({ fg = p.green_0, bg = nil }),
        RenderMarkdownH5Bg({ fg = p.white_0, bg = p.green_bg_0, gui = "bold" }),
        RenderMarkdownH6({ fg = p.blue_0, bg = nil }),
        RenderMarkdownH6Bg({ fg = p.white_0, bg = p.blue_bg_0, gui = "bold" }),
        RenderMarkdownTodo({ Todo }),
    }
end)

return theme
